### ISSUE TITLE
Feature Request: More beautiful Blog URL's

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#102]
It would be nice if the Blog URL would look a bit more like talking links.
Currently the URL's look like this:

![blogurl1](https://user-images.githubusercontent.com/24696577/55560639-ef64a100-56f0-11e9-9ca1-d6ea3622862b.png)
![blogurl2](https://user-images.githubusercontent.com/24696577/55560642-f2f82800-56f0-11e9-8585-4d94d2f8afdf.png)

It would be nicer to omit the first part, like this:
`http://pulse-5-3-1.test/A-Very-Nice-Blog-Post `
or
`http://pulse-5-3-1.test/another-title`

**Comment by ghost** [comment]
There is a Blog URL META field so it can be changed and the prefix can be changed

**Comment by oliver-77** [comment]
That's right. but you never get the word "blog" and the number(s) gone.
Whereby the word blog is not so bad I find. 
I find the numbers bothering. So you always have to think about generating the numbers string from Pulse or I enter a number myself to make it look a bit nicer.

With most blog engines the URL just looks like this:
`example.com/Another-Blog-Post`

**Comment by ghost** [comment]
Thinking this over this will be hard to do. The complications are:

- multiple and sub-blogs
- how to handle posts with the same title
- efficiency in the lookup between url and the blog txt file

Caching will fix some of this. But needs to be well thought out before proceeding.

**Comment by ghost** [comment]
This is done and ready for 5.3.3!

URLs of the form blog/A-Very-Nice-Blog-Post or blog/subblog/A-Very-Nice-Blog-Post are now supported

Note:

For this also, the old blog id url works too. So there is an extra URL format that also works
eg blog/A-Blog-Item or blog/zoo/A-New-Hippo

If the url prefix changes (eg to recipes, then the route is something like recipes/A-Pizza). The page loaded is recipes instead of blog in that case.

The idea is to have the new route for testing to see if it's a good fit. The route for this is handled differently from the others in dispatch.php, so its easier to add new ones.

If the dispatcher/router works well enough then the old blog URL rewrites in the .htaccess file could be removed. That would simplify the install too.

**Comment by oliver-77** [comment]
Thanks, sounds great.
