### ISSUE TITLE
Recent Posts not working vs 5.3.6

### ISSUE THREAD

**Issue by AceTutor** [yuzoolcode/pulsecms-tracking#116]
**Version 5.3.6**
Adding {{recentposts}} to a clean install is **not working**

**Recommendations** 

1. I would highly recommend that before a new revision is released, whoever "tweaks" your core software runs a live application of **all** Pulse core features to ensure they have not been affected. 

The current test pages shipped with Pulse should have a dedicated "**demo**" page showing a working example of every shipped plugin. If all legacy plugins on my suggested 'demo' page work following a "tweak", you will know that everything is OK to ship! 

_Sorry to have to spell out the obvious_!

2. The new 'version-history.md' file could also list what version of PHP is required and what modules are essential for complete operation.
Cheers

**Comment by ghost** [comment]
Thanks for the report

**Comment by ghost** [comment]
{{recentposts}} 

Seems to work for me...

<img width="1119" alt="Screenshot 2019-09-28 at 22 12 16" src="https://user-images.githubusercontent.com/4608547/65816989-1681d280-e23d-11e9-9a99-750f16b6d664.png">

- what are your settings for the tag? Just {{recentposts}} ?
- any errors in the logs?

**Comment by ghost** [comment]
- if it is PHP related.. what version are you running?
I'm on localhost MAMP with standard modules (default) version 7.1.6

**Comment by ghost** [comment]
- any shared hosting with standard modules will work
- we have more hosting information on this page:
http://pulsecms.com/hosting/
- it includes a server test
- the logs will also show anything in Pulse/extend
- virtual servers etc need standard PHP 7 installed 

As for the demo point, we test all the shipped items manually and run unit tests. Of course sometimes bugs creep in but it's hard as there are so many variables: users installing, different servers etc - that's why we include the logs to hopefully give clues as to what is missing. 

We will try and add more to the demo if not to show all the things it can do out the box, and that can also be a test case. But we run them already so not sure if Pulse users would appreciate a big demo as they've mentioned before it's a pain having to delete all the content pages..

**Comment by AceTutor** [comment]
Good call Michael. Thanks for closing issue.

I have not found what was missing that causes the errors. Since your comments I have loaded MAMP on my local system and {{recentposts}} worked fine.

Before making this report I also made a fresh install on a live server - that server still fails {{recentposts}} and I believed we had an issue. I have tried it since on yet another live server and here it works fine.

Next time I have an issue I will use MAMP as a proofing tool. Sorry to have called wolf without substance.
Cheers

**Comment by jrondorf** [comment]
Have you access to the php server log files?

**Comment by AceTutor** [comment]
Here is error message from log:
[30-Sep-2019 19:55:45 Australia/Brisbane] PHP Fatal error:  Declaration of pulsecore\tags\RecentPosts::generate_html(array $params = Array, array $tag_runner_context = Array, $tag_content = '') must be compatible with pulsecore\tags\Base::generate_html(array $params = Array, array $tag_runner_context = Array, string $tag_content = ''): string in /home/quvicmod/public_html/demo/pulsecore/tags/recentposts.php on line 7

You can check out the sites configuration at [http://demo.quvicmodels.com.au/test.php](http://demo.quvicmodels.com.au/test.php)

**Comment by ghost** [comment]
Hmmmm.. no idea why this happening
Will need more testing

**Comment by AceTutor** [comment]
Please stop looking.  I have been the author of the problem. I had corrupted recentposts.php unknowingly. Thanks for your patience and persistence to ensure a quality product.
