### ISSUE TITLE
5.3.7 Blog Tags

### ISSUE THREAD

**Issue by r3chn3r** [yuzoolcode/pulsecms-tracking#122]
They don't seem to be saving correctly.

**Comment by pcalej** [comment]
Hi @r3chn3r,
The blog tags in version 5.3.7 seem to be working perfectly on my end. Can you provide the following details so that we can look into it?
**OS:
Browser:
Screenshot/Video if available:**
I would highly appreciate if you can provide these. It'll allow our team to identify the root cause if there really is an issue and work on a solution as soon as possible.
Thanks!

**Comment by r3chn3r** [comment]
Thank you for following up on this.

It appears to be working as designed now.

Sorry for the inconvenience
