### ISSUE TITLE
Bug in WYSIWYG link to https in Redactor

### ISSUE THREAD

**Issue by ghost** [yuzoolcode/pulsecms-tracking#17]
> hi guys,
> 
> when i try to enter a HTTPS link the WYSIWYG removes the "s" after saving the block.
> 
> workaround: enter the s manually in HTML-Code View.
> 
> using pulse 5.0.1

It's a bug in Redactor 2.12
With a new Redactor update this should get fixed :) 

https://forum.pulsecms.com/t/link-module-wysiwyg-not-working-correctly-with-https/908

**Comment by isilher** [comment]
Hi @yuzoolcode, I came across this issue searching for a solution in my own project. So far this hasn't been fixed by imperavi yet. I found the problem comes from the [linkValidation](https://imperavi.com/redactor/docs/settings/link/#s-linkvalidation) that is by default 'fixing' any links you set. The following fixed the problem for me:

``` js
@element.redactor({
  // ...
  linkValidation: false,
})
```

**Comment by ghost** [comment]
Thanks for the note @isilher - we'll keep an eye on this one - have you tested this in latest Redactor 3?

**Comment by ghost** [comment]
Confirmed this still exists in Redactor 3.0.4

**Comment by oliver-77** [comment]
This means that the hope of using codemirror is over. :(

**Comment by ghost** [comment]
Yes...

Redactor 3.0.4 added for Pulse 5.1 so unless they bring this back we have to use the standard code editor view.
But at least it fixes the line breaks... a compromise I guess

**Comment by ghost** [comment]
Not sure when this will be ready... waiting on them... This will make it in a future release but most likely not 5.1

**Comment by ghost** [comment]
Fixed in Pulse 5.1 with Redactor 3.0.5 onwards
