### ISSUE TITLE
Can't center images

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#65]
Having an issue with the latest beta where I can't center images. I have to go in and manually add 
figure style="text-align: center;" to the code

**Comment by ghost** [comment]
This could be Redactor or could be the theme.

What theme are you using? Any links?

Cheers

**Comment by ghost** [comment]
Plugged in an update for the redactor alignment bug. The fix is to allow figures in the output (imageFigure setting for redactor).

This will be in the next update :) 

We had previously removed this in a previous update:
https://forum.pulsecms.com/t/how-to-add-a-single-image-lightbox/950/9?u=pulsecms
https://forum.pulsecms.com/t/images-are-reduced-to-50-in-size/1084

But it looks like we need this back to get the Redactor stylings applying. 

So in the case of targeting Lightbox will need to target through the Figure class too.
